### ISSUE TITLE
WebSocket connection to 'ws://localhost:8081/ws' failed

### ISSUE THREAD

**Issue by jpoep** [publiclab/Leaflet.DistortableImage#1323]
**Describe the bug:**
Whenever a page that has this package included is opened, the browser repeatedly attempts to connect to the WebPack dev server at `localhost:8081`. As I'm not using WebPack, this request constantly fails and it also happens in production. When you open your browser's dev tools, you can observe this behavior in the console. This also happens in the [demo site](https://publiclab.github.io/Leaflet.DistortableImage/examples/index.html).

![grafik](https://user-images.githubusercontent.com/11962438/210409725-809f9af2-7fa5-4c3b-b26c-7f33cd50bb3e.png)

It looks like the package is distributed with a development build, but I haven't looked too far into it. I'm not that familiar with the WebPack ecosystem.

**Reproduce the behavior:**
- Open any site running this plugin, e.g. <https://publiclab.github.io/Leaflet.DistortableImage/examples/index.html>
- Open your browser's dev tools
- Observe the console for connection errors

**Browser, version, and operating system:**
 - Happens in all browsers (tested with Chrome, Firefox, and Safari)
 - Versions 108.0.5359.98, 108.0.1, and  16.1 (18614.2.9.1.12) respectively
 - Platform: macOS Ventura

Any help is much appreciated, thanks a lot in advance! :)

**Comment by luke-z** [comment]
It seems like the problem has been fixed with the release 0.21.10 which somehow isn't available on npm.

The website you linked (https://publiclab.github.io/Leaflet.DistortableImage/examples/index.html) doesn't show the error anymore.

**Comment by jpoep** [comment]
Interesting, thanks for the update! Any idea who is responsible for publishing 0.21.10 on npm? I bet it's where 99% of people pull this library from and it's already been 3 months since the release.

**Comment by makrishna** [comment]
> It seems like the problem has been fixed with the release 0.21.10 which somehow isn't available on npm.
> 
> The website you linked (https://publiclab.github.io/Leaflet.DistortableImage/examples/index.html) doesn't show the error anymore.

Looks like it is not working with websocket builds, can someone have a work around for it.

**Comment by tap2k** [comment]
Im still having the same issue with 0.21.10 working with NextJS v13.

**Comment by tap2k** [comment]
Did anyone figure out a solution to fix this?

**Comment by Parrryy** [comment]
Yeah still having this issue.

**Comment by Mustafa-Hersi** [comment]
have anyone found a solution to this?

**Comment by yuri-karelics** [comment]
looks like the only way to fix that is to clone repository locally and make the production build with "npm run build" (I had to disable tests also in gruntfile, they didn't start). When files can be copied into your project from 'dist' folder instead of using NPM package. But keep in mind the latest version of the code in the repository has at least two bugs:
1. this fix should be reverted, it is wrong https://github.com/publiclab/Leaflet.DistortableImage/commit/21ad3c788e385a8998fcbec392843e745ebd3701
2. tooltip support implemented wrong, so if you don't need tooltip it will anyway be shown (empty one). Can be fixed with additional condition that 'this.tooltipText' is not empty before attaching the tooltip

If you don't want to do it yourself, just take from 'dist' folder in this fork https://github.com/Karelics/Leaflet.DistortableImage

P.S. maintainers (@jywarren ?) some unexplainable hell is happening with the repository, development build released into NPM, unstable updates merged into main branch so new release can be done without adjestments, ... In general your library looks so cool, but what happened in the last year, could you stabilize the situation, thank you!

**Comment by joric** [comment]
Same issue. Also, for the love of god, please help me with example. I can't hide/show the image. If I use distortableCollection toggling the layer doesn't hide the image, only toolbar. If I use layerGroup it hides the image, but doesn't show it back. Please help!  It's a single file you can run it locally. https://joric.github.io/maps/examples/remap/

**Comment by phase** [comment]
I got the same issue with the latest release. This package worked for me: https://www.npmjs.com/package/leaflet-distortableimage-updated Be sure to include [leaflet-toolbar](https://www.npmjs.com/package/leaflet-toolbar)

**Comment by Leni-Vienne** [comment]
Many thanks @yuri-karelics, your branch is awesome, plenty of huge fixes!
